export const LOGIN = 'LOGIN'
export const LOGGOUT = 'LOGGOUT'
export const USUARIO_VALIDADO = 'USUARIO_VALIDADO'
export const PEGAR_POSTS = 'PEGAR_POSTS'
export const DELETAR_CONTA = 'DELETAR_CONTA'
export const UPDATE_USER = 'UPDATE_USER'
export const TOKEN_VALIDADO = 'TOKEN_VALIDADO'


export default {
	TOKEN_VALIDADO,
	LOGGOUT,
	PEGAR_POSTS,
	DELETAR_CONTA,
	USUARIO_VALIDADO,
	UPDATE_USER
}